Update requirements.txt
Solving the error, when starting the application:
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.